import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"], weight: ["400", "600"] }); // 400 normal, 600 semi-bold

export const metadata: Metadata = {
  title: "Blog Rafael",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${inter.className} bg-main h-dvh lg:flex lg:items-center lg:justify-center `}>
        <div
          className="flex flex-col
          h-dvh
          lg:border-8 lg:border-gray-700 lg:rounded-3xl 
          lg:w-[1000px] lg:max-w-[95vw] 
          lg:max-h-[85vh]  
          lg:overflow-hidden"
        >
          <Header />
          <main
            className="flex-grow
          lg:max-h-[70vh] overflow-y-auto"
          >
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
